config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :blogs, only: [:update]

  get 'update_blog', to: 'blogs#edit', as: :update_blog

  # , :shallow => true do
  resources :posts
  devise_for :users
  root to: "home#index"
  get "/pages/:page" => "pages#show"
  get "/blogs/publish" => "blogs#publish_blog"
  # get '/users/password/new', to: redirect('/pages/forgot_password')
  get '*path' => redirect('/')

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_many :posts, :dependent => :destroy
  belongs_to :user

  def publish
    begin
      self.clean_folder()
      self.create_folder()
      self.update_config()
      self.update_about()
      self.update_cname()
      self.update_posts()
      self.deploy_github()
      self.clean_folder()
      self.last_published_at=Time.now
      self.last_published_status=true
    rescue
      self.last_published_at=Time.now
      self.last_published_status=false
    end
    self.save!
  end

  def path()
    "all_projects/#{self.name}_#{self.theme}"
  end

  def clean_folder()
    `rm -rf #{self.path}`
  end

  def create_folder()
    `cp -R themes/#{self.theme} #{self.path}`
  end

  def update_cname()
    if self.url!="#{Rails.configuration.lkp['base_url']}/#{self.name}/"
     File.write("#{self.path}/CNAME",
      self.url.chomp("/")
     )
    else
     File.write("#{self.path}/CNAME",
      ""
     )
    end
  end

  def get_baseurl()
    if self.url=="#{Rails.configuration.lkp['base_url']}/#{self.name}/"
      "/#{self.name}"
    elsif self.url=="#{Rails.configuration.lkp['base_url']}/#{self.name}"
      "/#{self.name}"
    else
      "/"
    end
  end

  def update_config()
      File.write("#{self.path}/_config.yml",
      <<-HEREDOC
title: #{self.title || Rails.configuration.lkp['default_name']}
email: #{self.email || Rails.configuration.lkp['default_email']}
description: > # this means to ignore newlines until "baseurl:"
 #{self.description.gsub(/\n/, " ").strip()}

baseurl: "/" # the subpath of your site, e.g. /blog
url: "#{self.url.chomp("/")}" # the base hostname & protocol for your site
twitter_username: #{self.twitter || Rails.configuration.lkp['default_twitter']}

markdown: kramdown

name: #{self.title || Rails.configuration.lkp['default_name']}

date: #{Time.now}
permalink: /:year/:month/:day/:title

logo: false
paginate: 10
adsid: ca-pub-8582082279264878
domain_name: #{self.url}
google_analytics: #{self.google_analytics}
gems: [jekyll-paginate]
cover: #{self.cover_image}
author_image: #{self.author_image}
# Details for the RSS feed generator
author:        #{self.author_name}
      HEREDOC
      )
  end

  def update_about()
      File.write("#{self.path}/about.md",
      <<-HEREDOC
---
layout: page
title: About
permalink: /about/
---

#{self.about || Rails.configuration.lkp['default_about']}
      HEREDOC
      )
  end

  def update_posts()
    for post in self.posts.where("mark_work_in_progress IS NULL OR mark_work_in_progress = ?", false) do
      File.write("#{self.path}/_posts/#{post.path}", post.header+"\n"+"\n"+post.content)
    end
  end

  def deploy_github()
    `cd #{self.path} && git init && git add --all && git checkout -b #{Rails.configuration.lkp['branch']} && git commit -m "first commit" && git remote add origin https://github.com/#{Rails.configuration.lkp['gitusername']}/#{self.user.username} && git push -f origin #{Rails.configuration.lkp['branch']}`
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :publish_blog]
  include BlogsHelper

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    @blog.update(blog_params)
    @blog.url=clean_url(blog_params[:url])
    respond_to do |format|
      if @blog.save
        format.html { redirect_to :update_blog, notice: 'Blog was successfully updated, don\'t forget to publish changes.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def publish_blog
    @blog.publish()

    respond_to do |format|
      if @blog.last_published_status
        format.html { redirect_to :root, notice: "Blog was successfully published at #{Time.now}. Changes may take upto 5 minutes to reflect." }
      else
        format.html { redirect_to :root, alert: "Please publish again, failed at #{Time.now}." }
      end
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      if params[:id]
        @blog = Blog.find(params[:id])
      else
        @blog = current_user.blogs.first
      end
      if @blog.user_id!=current_user.id
        @blog = nil
        respond_to do |format|
          format.html { redirect_to :root, notice: 'Uauthorized access.' }
          format.json { head :no_content }
        end
      else
        @blog
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:email,:description,:twitter,:about, :title, :author_name, :author_image, :cover_image, :google_analytics, :theme, :url)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def clean_url(url)
    regx=/:\/\//
    if regx.match(url)
      url
    else
      'http://'+url
    end
  end
end

app/views/blogs/_form.html.erb
<%= simple_form_for(@blog) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, disabled: true %>
    <p class="help-block">You can't change
      <a target="_blank" href="/pages/learn_more/#question-can-i-change-my-username-">
        name</a>
    </p>
  </div>

  <div class="form-inputs">
    <%= f.input :title,hint: 'Title for your blog.' %>
  </div>

  <div class="form-inputs">
    <%= f.input :author_name %>
  </div>

  <div class="form-inputs">
    <%= f.input :url %>
    <p class="text-danger">
      <font color='grey'>Use your own custom url.</font> Don't change this before
      <a target="_blank" href="/pages/learn_more/#question-how-do-i-use-custom-url-for-my-blog-">reading how guide.</a>
      <br>
      <a id="reset_url" href="#">reset url</a>
    </p>
  </div>
  <script>
  $(function() {
    return $("#reset_url").click(function(e) {
      e.preventDefault();
      $("#blog_url").val("<%= Rails.configuration.lkp['base_url']+'/'+current_user.username+'/' %>")
      $('form').submit();
    });
    });
  </script>

  <div class="form-inputs">
    <%= f.input :description, as: :text %>
  </div>

  <div class="form-inputs">
    <%= f.input :theme, collection: [ "minima", "kasper"], as: :radio_buttons %>
    <p class="help-block">
      <a target="_blank" href="/pages/learn_more/#question-how-many-themes-are-there-on-cyobb-">Preview of themes</a>
    </p>
  </div>

  <div class="form-inputs">
    <%= f.input :email %>
  </div>

  <div class="form-inputs">
    <%= f.input :cover_image %>
    <p class="help-block">
      Cover image for your blog.
      <a target="_blank" href="/pages/learn_more/#question-how-to-upload-images-in-posts-and-for-cover-photo-and-for-author-image-">Upload Images</a>
    </p>
  </div>

  <div class="form-inputs">
    <%= f.input :author_image %>
  </div>

  <div class="form-inputs">
    <%= f.input :google_analytics %>
    <p class="help-block">
      Google tracking code.
      <a target="_blank" href="/pages/learn_more/#question-how-to-track-visitors-on-my-blog-by-google-analytics-">How to get id?</a>
    </p>
  </div>

  <div class="form-inputs">
    <%= f.input :twitter, hint: 'Your twitter username' %>
  </div>

  <div class="form-inputs">
    <%= f.input :about ,as: :text,input_html: { id: 'about_box' } %>
    <p class="help-block">
      <a target="_blank" href="/pages/learn_more/#question-what-is-markdown-editor-how-to-use-it-">More info about editor</a>
    </p>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>


<script>
  var simplemdeA;
  setTimeout(function(){
      if( /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) ) {
       // some code..
     }else{
       if (simplemdeA){
         location.reload()
       }else{
        simplemdeA = new SimpleMDE({ element: document.getElementById("about_box") });
       }
     }
    }, 300);
</script>

app/views/blogs/edit.html.erb
<h1>Edit all your blog details at one place</h1>

<%= render 'form', blog: @blog %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.name %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @blog.name %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>