config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :blogs, only: [:update]

  get 'update_blog', to: 'blogs#edit', as: :update_blog

  # , :shallow => true do
  resources :posts
  devise_for :users
  root to: "home#index"
  get "/pages/:page" => "pages#show"
  get "/blogs/publish" => "blogs#publish_blog"
  # get '/users/password/new', to: redirect('/pages/forgot_password')
  get '*path' => redirect('/')

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Create Your Own Beautiful Blog with automated jekyll on github pages</title>
    <%= csrf_meta_tags %>
    <meta name=viewport content="width=device-width, initial-scale=1">
    <meta http-equiv="Cache-control" content="public">
    <meta name="description" content="<%= Rails.configuration.lkp['description'] %>">
  <meta name="keywords" content="<%= Rails.configuration.lkp['keywords'] %>">
  <meta property="og:title" content="Create Your Own Beautiful Blog with automated jekyll on github pages">
  <meta property="og:image" content="<%= image_url 'kasper.png'%>">
  <meta property="og:description" content="<%= Rails.configuration.lkp['description'] %>">
  <%= favicon_link_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', :async => true %>

    <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js" async></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.6/marked.min.js" async></script>
    <!-- google recaptcha -->
    <script src='https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit' async defer></script>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-82100511-2', 'auto');
      ga('send', 'pageview');

    </script>
  </head>
  <% style="background: url(" + image_url('home.jpg') + ") no-repeat" %>
  <body style="<%= style if !current_user && ['registrations','home','sessions'].include?(controller_name) %>">
    <nav class="navbar navbar-default">
      <div class="container-fluid container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><%= Rails.configuration.lkp['title'] %></a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">

          </ul>

          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li><%= link_to('Text editor guide', 'https://simplemde.com/markdown-guide',{target: '_blank'}) %></li>
              <li><%= link_to('Update blog details', update_blog_path) %></li>
              <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
            <% else %>
              <li><%= link_to "Sign up", new_registration_path(resource_name) %></li>
              <li><%= link_to "Log in", new_session_path(resource_name) %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <main>
        <div class="row">
          <div class="col-md-9 little-padding">
            <% if !current_user %>
              <h4 class="help-block">Automated jekyll build on github pages</h4>
            <% end %>
            <% if notice %>
              <p class="alert alert-success"><%= notice %></p>
            <% end %>
            <% if alert %>
              <p class="alert alert-danger"><%= alert %></p>
            <% end %>
            <%= yield %>
          </div>
          <div class="col-md-3">
            <h2>Look Ups</h2>
            <% if current_user %>
              <div class="panel panel-default">
                <div class="panel-body">
                  Your blog is published at<br>
                  <a href="<%= current_user.blogs.first.url %>" target="_blank">
                    <%= current_user.blogs.first.url %>
                  </a>
                  <p class="help-block">
                    You can use your own custom url
                    <a target="_blank" href="/pages/learn_more/#question-how-do-i-use-custom-url-for-my-blog-">how?</a>
                  </p>
                </div>
              </div>

              <div class="panel panel-default">
                <div class="panel-heading">Publish the changes</div>
                <div class="panel-body">
                  <a href="/blogs/publish" class="btn btn-primary btn-lg" data-disable-with="Please wait... ">Publish Changes</a><br>
                  Changes may take upto 5 minutes to reflect.
                </div>
              </div>

              <div class="panel panel-default">
                <div class="panel-body">
                  You have written
                  <%= current_user.blogs.first.posts.count %> posts.
                </div>
                <div class="panel-footer">
                <% if current_user.blogs.first.last_published_status %>
                  <span class="label label-success">Success</span>
                  Last published at <%= current_user.blogs.first.last_published_at %>
                <% else %>
                  <span class="label label-danger">Failed</span>
                  Please publish again, failed at <%= current_user.blogs.first.last_published_at %>
                <% end %>
                </div>
              </div>
            <% else %>
              <div class="panel panel-default">
                <div class="panel-body">
                  Your blog will be published at<br>
                  <%= Rails.configuration.lkp['base_url'] %>/username
                  <p class="help-block">
                    You can use your own custom url
                    <a target="_blank" href="/pages/learn_more/#question-how-do-i-use-custom-url-for-my-blog-">how?</a>
                  </p>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </main>

      <% if !current_user %>
        <br>
        <br>
        <div class="panel panel-default">
           <div class="panel-heading">
              All available themes
           </div>
          <div class="panel-body">
            <% all_themes().each do |i| %>
              <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
                  <div class="hovereffect">
                      <%= image_tag(i[:image], class: "img-responsive") %>
                          <div class="overlay">
                              <h2><%= i[:name] %></h2>
                      <p>
                        <a href="<%= i[:link] %>">Preview</a>
                      </p>
                          </div>
                  </div>
              </div>
            <% end %>
          </div>
        </div>
        <p class="help-block">More themes coming soon.</p>
      <% end %>

      <div class="jumbotron">
        <h1>Explain the concept</h1>
        <h5 class="help-block">Automated jekyll build on github pages</h5>
        <div class="list-group">
          <a href="/pages/learn_more/#question-what-happens-when-i-create-account-" class="list-group-item">
            <h4 class="list-group-item-heading">Create account</h4>
            <p class="list-group-item-text">
              After you sign up we create and publish your blog online at cyobb.com/username.
            </p>
          </a>
          <a href="/pages/learn_more/#question-how-to-upload-images-in-posts-and-for-cover-photo-and-for-author-image-" class="list-group-item">
            <h4 class="list-group-item-heading">Add and edit posts</h4>
            <p class="list-group-item-text">
              You can add and edit your posts anytime by logging into your account.
            </p>
          </a>
          <a href="/pages/learn_more/#question-how-many-themes-are-there-on-cyobb-" class="list-group-item">
            <h4 class="list-group-item-heading">Update theme</h4>
            <p class="list-group-item-text">
              You can also change your blog's theme from available options, on update blog details page.
            </p>
          </a>
          <a href="/pages/learn_more/#question-changes-i-can-make-on-update-blog-details-page-" class="list-group-item">
            <h4 class="list-group-item-heading">Update blog details</h4>
            <p class="list-group-item-text">
              You can update all your blog details like about us page, blog's description, your email id, your twitter id, update theme, custom url, google tracking code right at one place.
            </p>
          </a>
          <a href="/pages/learn_more/#question-why-don-t-automatically-publish-changes-" class="list-group-item">
            <h4 class="list-group-item-heading">Publish changes</h4>
            <p class="list-group-item-text">
              All the changes and new posts will not be published to your blog until you publish them by clicking publish changes button.
            </p>
          </a>
          <a href="/pages/learn_more/#question-how-do-i-use-custom-url-for-my-blog-" class="list-group-item">
            <h4 class="list-group-item-heading">Custom url</h4>
            <p class="list-group-item-text">
              By default your blog's url will be cyobb.com/username. But you can buy your own url from godaddy.com and update your custom url in update blog details page.
            </p>
          </a>
        </div>
        <p><a class="btn btn-primary btn-lg" href="/pages/learn_more">Learn more</a></p>
      </div>


      <footer>Copyright &copy; 2017 <a href="https://github.com/rajatsingla">Rajatsingla.in</a> (rajatrs5054 at gmail.com)</footer>
    </div>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
  </body>
</html>